const courses = [
 {id:'speaking',title:'English Communication',duration:'2 months',price:1200,theme:'speaking',desc:'Learn to speak English fluently in real-life conversations.',includes:['Daily live 1:1','Speaking practice','Vocabulary']},
 {id:'basics',title:'Learn English from Basics',duration:'2 months',price:1200,theme:'basics',desc:'A friendly path from alphabet to confident sentences.',includes:['Sentence building','Daily exercises','Worksheets']},
 {id:'grammar',title:'Too Good at Grammar',duration:'1 month',price:1500,theme:'grammar',desc:'Build strong, clear English with practical grammar.',includes:['Tenses','Voice','Practice quizzes']},
 {id:'interview',title:'Interview & Soft Skills',duration:'1 month',price:1500,theme:'interview',desc:'Show up prepared, poised and ready to impress.',includes:['HR practice','Resume guidance','Group discussion']},
 {id:'confidence',title:'Build Speaking Confidence',duration:'1 month',price:1000,theme:'confidence',desc:'Find your voice through gentle, daily fluency practice.',includes:['Public speaking','Fear removal','Body language']},
 {id:'excel',title:'Learn Excel',duration:'2 months',price:1200,theme:'excel',desc:'Move from basics to practical spreadsheets, formulas and polished reports.',includes:['Live 1:1','Formulas','Projects']},
 {id:'ai',title:'Learn AI Tools',duration:'1 month',price:1500,theme:'ai',desc:'Use modern AI tools confidently for study, work and creativity.',includes:['Live 1:1','AI prompts','Hands-on tasks']},
 {id:'deepai',title:'Deep AI Learning',duration:'2 months',price:1500,theme:'ai',desc:'Master advanced AI models, neural networks and machine learning engineering.',includes:['Live 1:1','AI models','Deep learning projects']},
 {id:'literature',title:'Study English Literature',duration:'3 months',price:1200,theme:'basics',desc:'Explore timeless classics and modern works with expert analysis and discussion.',includes:['Live seminars','Critical analysis','Essay writing']}
];
let cart = JSON.parse(localStorage.getItem('mystic-cart') || '[]');
const money = n => `₹${n.toLocaleString('en-IN')}`;
function renderCourses(){document.querySelector('#course-list').innerHTML=courses.map(c=>`<article class="course-card"><div class="course-image ${c.theme}"><span class="duration">${c.duration} · Live 1:1</span></div><div class="course-info"><div class="top-course"><h3>${c.title}</h3><span class="rating">★ 4.9</span></div><p>${c.desc}</p><div class="inclusions">${c.includes.map(i=>`<span>${i}</span>`).join('')}</div><div class="course-bottom"><div class="price"><b>${money(c.price)}</b>/month</div><div class="course-buttons"><button class="details-btn" onclick="details('${c.id}')">Details</button><button class="add-btn" onclick="add('${c.id}')">Add to cart</button></div></div></div></article>`).join('')}
function add(id){if(!cart.includes(id)){cart.push(id);localStorage.setItem('mystic-cart',JSON.stringify(cart));toast('Added to your cart ✦');renderCart();}else toast('This course is already in your cart');}
function remove(id){cart=cart.filter(x=>x!==id);localStorage.setItem('mystic-cart',JSON.stringify(cart));renderCart()}
function renderCart(){const chosen=courses.filter(c=>cart.includes(c.id)), orig=chosen.reduce((s,c)=>s+c.price,0), rate=orig ? (chosen.length===courses.length ? .30 : .20) : 0, discount=Math.round(orig*rate), final=orig-discount;document.querySelector('#cart-count').textContent=cart.length||'';document.querySelector('#cart-items').innerHTML=chosen.map(c=>`<div class="cart-item"><div class="cart-img ${c.theme}"></div><div class="cart-info"><h3>${c.title}</h3><p>${c.duration} · ${money(c.price)}/month</p></div><button onclick="remove('${c.id}')">Remove</button></div>`).join('');document.querySelector('#cart-empty').classList.toggle('hidden',!!chosen.length);document.querySelector('#cart-summary').classList.toggle('hidden',!chosen.length);if(chosen.length){document.querySelector('#original-total').textContent=money(orig);document.querySelector('#discount-total').textContent='− '+money(discount);document.querySelector('#final-total').textContent=money(final);document.querySelector('#saving').textContent=`You saved ${money(discount)} on your first purchase`;document.querySelector('.coupon b').textContent=`−${rate*100}%`;}}
function details(id){const c=courses.find(c=>c.id===id);toast(`${c.title}: ${c.duration} of live 1:1 sessions, notes & practice included`)}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2700)}
function navigate(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.nav===id));window.scrollTo({top:0,behavior:'smooth'});}
document.addEventListener('click',e=>{const target=e.target.closest('[data-nav]');if(target)navigate(target.dataset.nav)});renderCourses();renderCart();
